name: Windows RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      - name: Install ngrok
        run: choco install ngrok

      - name: Authenticate ngrok
        run: ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Enable Remote Desktop
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "@cyb3rking" -Force)

      - name: Start ngrok tunnel in background
        run: Start-Process ngrok -ArgumentList 'tcp 3389' -NoNewWindow

      - name: Wait for ngrok to start
        run: Start-Sleep -Seconds 10

      - name: Get public ngrok endpoint
        shell: pwsh
        run: |
          $tunnels = Invoke-RestMethod http://127.0.0.1:4040/api/tunnels
          $endpoint = $tunnels.tunnels.public_url
          Write-Host "`n✅ RDP endpoint (copie no app Remote Desktop): $endpoint`n"
